### ISSUE TITLE
Add support for custom fields for specific calendars

### ISSUE THREAD

**Issue by te-online** [te-online/wordpress-plugin--themeable-calendar#32]
In the calendar setting the user can add custom fields (textinput, options select with predefined options). Those will show in the edit modal and the legacy edit screen in a separate meta box.

### Tasks
- [x] Add UI to term option view that helps with adding custom fields
  - [x] Add textinputs (`name`, `placeholder`, `label`)
  - [x] Add selectbox (`name`, `options`, `label`)
- [x] Show custom fields in legacy edit view
- [x] Show custom fields in calendar edit modal
- [x] Save custom fields values in calendar
- [x] Save custom fields values in legacy editor
- [x] Add a way to display the custom field values in templates

### Idea
- Maybe use ACF instead? https://www.advancedcustomfields.com/resources/acf_form/
